### ISSUE TITLE
RFE: don't import squashed image to docker, instead provide path to tarball

### ISSUE THREAD

**Issue by TomasTomecek** [goldmann/docker-scripts#23]
We're planning to push squashed image to pulp registry. Pulp understands tarballs, not docker images. Therefore we could optimize our workflow from:

1. squash image
 * export image as tarball from docker
 * squash it
 * import tarball as image back to docker
2. export image as tarball from docker
3. compress it
4. push to pulp

to

1. squash image
 * export image as tarball from docker
 * squash it
3. compress tarball (squashed image)
4. push to pulp

Therefore, would it be possible to create a switch or something for such functionality?

**Comment by goldmann** [comment]
Good idea, an option for this will be created, my proposal is to use `--load`. This would be set to `True` by default.

**Comment by TomasTomecek** [comment]
Sounds good to me (bear in mind we don't use cli :)

**Comment by goldmann** [comment]
Of course, I know :)

**Comment by goldmann** [comment]
One question - if we do not load automatically, where the image should be stored on the disk? Maybe instead of `--load`, we could define `--output-dir`. If it would be set, it would mean that you're not interested in loading, but you want the image to have stored in the specific directory. Any other ideas?

Another question is about the tar file name. Is `image.tar` ok? This would make it easy to "guess" what it would be for later processing.

**Comment by goldmann** [comment]
Or even better `--output-path` that would define where the image should be stored, like: `/opt/builds/eap/build-abc-squashed.tar`.

**Comment by TomasTomecek** [comment]
I vote for `--output-path`; then it will be up to user to specify name and path.

**Comment by TomasTomecek** [comment]
Thanks Marek! CC @twaugh

**Comment by goldmann** [comment]
Released `0.3.10.dev0`.
