### ISSUE TITLE
(docker-v110) Fails with mixed-layer image

### ISSUE THREAD

**Issue by twaugh** [goldmann/docker-scripts#52]
I'm using the docker-v110 branch. When building an image with docker 1.10 that inherits from an image built with docker < 1.10, squashing fails.

```
# docker build --rm -t mixed .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> 3240943c9ea3
Step 2 : CMD /bin/env
 ---> Running in 4dc560c8c72b
 ---> f3f397aee4b0
Removing intermediate container 4dc560c8c72b
Successfully built f3f397aee4b0

# docker history mixed
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
f3f397aee4b0        2 minutes ago       /bin/sh -c #(nop) CMD ["/bin/sh" "-c" "/bin/e   0 B                 
3240943c9ea3        8 days ago          /bin/sh -c #(nop) CMD ["sh"]                    0 B                 
<missing>           8 days ago          /bin/sh -c #(nop) ADD file:7cdf7a89f6a004b2e9   1.114 MB            

# docker-scripts squash mixed -t mixed:squashed
2016-02-25 11:14:05,730 root         INFO     docker-scripts version 1.0.0a1, Docker c3959b1, API 1.22...
2016-02-25 11:14:05,731 root         INFO     Using v2 image format
2016-02-25 11:14:05,738 root         ERROR    Could not get the layer ID to squash, please check provided 'layer' argument: <missing>
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 89, in run
    args.func(args)
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 32, in run_squash
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir).run()
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 68, in run
    new_image_id = image.squash()
  File "build/bdist.linux-x86_64/egg/docker_scripts/image.py", line 65, in squash
    self._before_squashing()
  File "build/bdist.linux-x86_64/egg/docker_scripts/v2_image.py", line 15, in _before_squashing
    super(V2Image, self)._before_squashing()
  File "build/bdist.linux-x86_64/egg/docker_scripts/image.py", line 130, in _before_squashing
    "Could not get the layer ID to squash, please check provided 'layer' argument: %s" % from_layer)
SquashError: Could not get the layer ID to squash, please check provided 'layer' argument: <missing>
```

**Comment by goldmann** [comment]
I can confirm this bug.

It appears when the squashed image is a mixed image, which means contains layers created by earlier version of docker as well as with new version (>= 1.10). This is a common case where you base your image on some older image not built by version 1.10.

Currently the logic to retrieve the ID of the layer to squash does not work in such case, because the `docker history` call on the image to squash will list the old layers as `<missing>`. I'm in the process of finding a workaround for it.

To visualise it, compare this output from Docker 1.9:

```
$ docker history ubuntu:14.04
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
e9ae3c220b23        3 months ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
a6785352b25c        3 months ago        /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB            
0998bf8fb9e9        3 months ago        /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   194.5 kB            
0a85502c06c9        3 months ago        /bin/sh -c #(nop) ADD file:531ac3e55db4293b8f   187.7 MB
```

With output from Docker 1.10

```
$ docker-1.10 -H unix:///tmp/docker-v2.sock history ubuntu:14.04

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
e17b56e5200a        9 hours ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
<missing>           9 hours ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB            
<missing>           9 hours ago         /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   194.5 kB            
<missing>           9 hours ago         /bin/sh -c #(nop) ADD file:ea70c09b264ee09dcd   187.7 MB
```

Same image, but different versions of Docker.

**Comment by goldmann** [comment]
I do see one possibility to make to make this work. Instead of defining the layer to squash from, the tool would require number of layers to squash instead. In such case I would not lookup the layer id prior squash and it would just get the ID from the exported tar which should be simple. Of course this would change the API, but I plan to release v2 image support as version 1.0.0 so this wouldn't hurt. Any comments?

**Comment by goldmann** [comment]
Some other notes - I do some pre-checks before squashing, like:

* does the layer exists in the image?
* do we really need to squash?

This is where it fails.

But I do not want to drop them from the code, because I do think that failing early in case if issues makes sense, especially when we're talking about a very resource consuming task like creating the image tarball. I want to do anything I can before the tarball is generated to do this only if I'm sure squashing will be possible.

After a bit of thinking about the implementation I propose following:

1. Add a `--number` (`-n`) argument to CLI (and API of course) which specifies number of layers to squash.
2. Do not remove `--from` argument from the tool.
3. If `--number` and `--from` is specified, `--number` takes precedence, a warning is logged that `--from`. is ignored
4. If `--from` is specified and the layer ID could not be determined, fail as we fail today with message suggesting that this is probably a mixed image and in such case using `--number` is suggested.

And last note: this issue does not affect squashing images created entirely in Docker pre 1.10 or created entirely with Docker 1.10+. This affects images created with Docker pre 1.10 with added some layers using Docker 1.10+. This issue is intermediate until images will be converted to new format.

**Comment by twaugh** [comment]
The number of layers to squash, or the number of layers *not* to squash? Would we have to count the layers to know what to pass in for that parameter?

Ideally, we would only have to know how many layers are in the parent image, and have all the inherited layers below that squashed together.

**Comment by goldmann** [comment]
Number of layers to squash. Yes, in case you want to squash a mixed image you would need to count layers. A bit pain in the butt, but at least it would work.

But once again - this is only for a limited tine when there images exist in new and old formst together. If you squash images built in one or the other fornat entirely - you will be able to use `--from`.

Btw, at the squash time we don't know how many layers the parent image has.

**Comment by goldmann** [comment]
I think this should be now done, test it hard and report all issues.
